# Generated by Django 2.1.5 on 2019-05-26 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190526_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 18, 54, 19, 133309, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 18, 54, 19, 133309, tzinfo=utc)),
        ),
    ]
